# Generated by Django 4.0.5 on 2022-08-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_name', models.CharField(max_length=200)),
                ('Text_file', models.FileField(upload_to='')),
            ],
        ),
    ]
