# Generated by Django 4.0.5 on 2022-08-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_rename_text_file_textfile_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextFile',
            new_name='UserFile',
        ),
    ]
