# Generated by Django 4.0.5 on 2022-08-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_rename_textfile_userfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('msg', models.CharField(max_length=300)),
            ],
        ),
    ]
