# Generated by Django 4.0.5 on 2022-08-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_userfeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfeedback',
            old_name='username',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='msg',
            field=models.TextField(max_length=300),
        ),
    ]
