# Generated by Django 4.0.5 on 2022-08-31 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_rename_username_userfeedback_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfile',
            old_name='File',
            new_name='files',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='File_name',
        ),
    ]
